name: Schedule Test

on:
  schedule:
    - cron: '*/5 * * * *'
      timezone: 'Asia/Kolkata'

  workflow_dispatch:

jobs:
  test-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Check scheduled trigger
        run: |
          echo "Scheduled workflow triggered successfully"
          date